spring:
  datasource:
    password: root123
    url: jdbc:mysql://localhost:3306/zensar
    username: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format-sql: true
      # dialect: org.hibernate.dialect.MySQLDialect
      